databases:
  - name: jkexpress-db
    plan: free
    databaseName: jkexpress
    user: jkexpress

services:
  - type: web
    name: jkexpress
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jkexpress-db
          property: connectionString
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: AUTH_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
